/*==============================================================================
    Project_HOGE
    [CObjectManager.cs]
    ï¿½Eï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ç—ï¿½
--------------------------------------------------------------------------------
    2021.04.22 @Author Suzuki Hayase
================================================================================
    History
        210426 Suzuki
            ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½ï¿½ï¿½Ô‚ï¿½lï¿½ß‚ï¿½æ‚¤ï¿½ï¿½
        210517 Ono
            ã‚¹ãƒ†ãƒ¼ãƒˆå‡¦ç†ã®èª¿æ•´
        210525 Sasaki
            ãƒãƒ¼ã‚ºç”»é¢ã®æ™‚ã«ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆãŒå›è»¢ã—ãªã„ã‚ˆã†ãªå‡¦ç†è¿½åŠ (60~63è¡Œç›®)
        
/*============================================================================*/
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

// ï¿½ï¿½]ï¿½ï¿½Ô‚Ì—ñ‹“Œ^
public enum RotateState {
    INSIDE,
    OUTSIDE
}

public enum OBJECT_SHAPE {                     // ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ÌŒ`ï¿½ï¿½
    CUBE,
    SPHERE,
    TRIANGLE,
    RAMIEL,
    STELLA,
    HOURGLASS,
    SATURN,
    TRIPLE,
    MAX
}

public class CObjectManager : CSingletonMonoBehaviour<CObjectManager> {
    [SerializeField] private List<GameObject> gObjectList = new List<GameObject>();     // ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½Xï¿½g
    [SerializeField] private List<GameObject> gAcceleList = new List<GameObject>();     // ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½Xï¿½g
    [SerializeField] private List<OBJECT_SHAPE> CreateList = new List<OBJECT_SHAPE>();  // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Xï¿½g

    [SerializeField] private GameObject[] gObjectSource;          // ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½\ï¿½[ï¿½X
    [SerializeField] private float fInterval;                     // ï¿½zï¿½uï¿½ÔŠu
    [SerializeField] private float fSpeed;                        // ï¿½ï¿½]ï¿½Xï¿½sï¿½[ï¿½h
    [SerializeField] private float fAcceleSpeed;                  // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½]ï¿½Xï¿½sï¿½[ï¿½h
    [SerializeField] private float fInRadius;                     // ï¿½ï¿½ï¿½è”¼ï¿½a
    [SerializeField] private float fOutRadius;                    // ï¿½Oï¿½ï¿½è”¼ï¿½a

    private int iTimer = 0;                                       // ï¿½ï¿½ï¿½ï¿½ï¿½ÔŠuï¿½^ï¿½Cï¿½}ï¿½[

    // Start is called before the first frame update
    void Start() {

    }

    // Update is called once per frame
    void Update() {
        // ãƒãƒ¼ã‚ºç”»é¢ã®æ™‚ã«ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆãŒç”Ÿæˆã—ãªã„ã‚ˆã†ãªå‡¦ç†
        if (Mathf.Approximately(Time.timeScale, 0f)) {
            return;
        }

        // ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆç”Ÿæˆ
        if (CreateList.Count > 0) {
            if (iTimer >= 60) {
                // ï¿½dï¿½È‚ï¿½È‚ï¿½ï¿½æ‚¤ï¿½Éï¿½ï¿½ï¿½ï¿½Ê’uï¿½ğ’²ï¿½
                float sd = 180.0f;
                float rad = 9.0f;
                RotateState rs = RotateState.OUTSIDE;
                if (gObjectList.Count > 0) {
                    float ld = gObjectList[gObjectList.Count - 1].GetComponent<CRotateObject>().Get_fDegree();

                    if (ld >= 190 && ld <= 520) {
                        sd = 180;
                        rad = fOutRadius;
                        rs = RotateState.OUTSIDE;
                    }
                    else {
                        sd = 520;
                        rad = fInRadius;
                        rs = RotateState.INSIDE;
                    }
                }
                Vector3 pos = new Vector3(rad * Mathf.Sin((sd + 180) * Mathf.Deg2Rad),
                                          0.0f,
                                          rad * Mathf.Cos((sd + 180) * Mathf.Deg2Rad));

                // ï¿½ï¿½ï¿½ï¿½
                GameObject tmp = Instantiate(gObjectSource[(int)CreateList[0]], pos,
                    Quaternion.Euler(0, 0, 0));

                // ï¿½pï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½^ï¿½Zï¿½bï¿½g
                CRotateObject cs = tmp.GetComponent<CRotateObject>();
                cs.Set_fDegree(sd);
                cs.Set_Shape(CreateList[0]);
                cs.Set_State(rs);

                tmp.GetComponent<CRotateObject>().Set_isAccele(true);

                CreateList.RemoveAt(0);

                gAcceleList.Add(tmp);

                iTimer = 0;
            }
            iTimer++;
        }

        if (GameObject.Find("PFB_Gate(Clone)") == null) {
            OBJECT_SHAPE first = COrderManager.Instance.Get_Order(0);
            Sort(first);
        }

        for (int i = 0; i < gObjectList.Count; i++) {
            gObjectList[i].GetComponent<CRotateObject>().UpdateObject();
        }
        for(int i = 0; i < gAcceleList.Count; i++) {
            gAcceleList[i].GetComponent<CRotateObject>().UpdateObject();
        }
    }

    // ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆç”Ÿæˆé–¢æ•°
    public void Create(int n) {
        // ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½Èï¿½ï¿½ï¿½ï¿½Å”zï¿½u
        List<int> nums = new List<int>();
        for (int i = 0; i < CLevelManager.Instance.Get_iObjectNum(); i++) {
            nums.Add(i);
        }

        // ï¿½dï¿½ï¿½ï¿½ï¿½ï¿½È‚ï¿½ï¿½æ‚¤ï¿½ï¿½
        for (int i = 0; i < CreateList.Count; i++) {
            nums.Remove((int)CreateList[i]);
        }

        for (int i = 0; i < gObjectList.Count; i++) {
            CRotateObject cro = gObjectList[i].GetComponent<CRotateObject>();
            nums.Remove((int)cro.Get_Shape());
        }

        for(int i = 0; i < gAcceleList.Count; i++) {
            CRotateObject cro = gAcceleList[i].GetComponent<CRotateObject>();
            nums.Remove((int)cro.Get_Shape());
        }

        // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Xï¿½gï¿½É’Ç‰ï¿½
        for (int i = 0; i < n; i++) {
            int rand = Random.Range(0, nums.Count);
            CreateList.Add((OBJECT_SHAPE)nums[rand]);
            nums.RemoveAt(rand);
        }
    }

    // ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆãƒªã‚¹ãƒˆã«è¿½åŠ 
    public void Add(GameObject g) {
        if (!gObjectList.Contains(g)) {
            gObjectList.Add(g);
        }
    }

    // ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆãƒªã‚¹ãƒˆã‹ã‚‰å‰Šé™¤
    public void Remove(GameObject g) {
        if (gObjectList.Contains(g)) {
            gObjectList.Remove(g);
        }
        if (gAcceleList.Contains(g)) {
            gAcceleList.Remove(g);
        }
    }

    public void Accele(GameObject g) {
        Remove(g);
        gAcceleList.Add(g);
    }

    public void Decelerate(GameObject g) {
        gAcceleList.Remove(g);
        Add(g);
    }

    public void AddCreateList(OBJECT_SHAPE first) {
        CreateList.Add(first);
    }

    // æŒ‡å®šã—ãŸã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã‚’å…ˆé ­ã«
    public void Sort(OBJECT_SHAPE first) {
        // ï¿½æ“ªï¿½É‚ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½indexï¿½æ“¾
        int firstid = 0;
        GameObject firstobj = null;
        for (int i = 0; i < gObjectList.Count; i++) {
            if (gObjectList[i].GetComponent<CRotateObject>().Get_Shape() == first) {
                firstobj = gObjectList[i];
                firstid = i;
                break;
            }
        }

        if (firstid == 0) {
            return;
        }
        
        // ï¿½×–ï¿½ï¿½ÈƒIï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        for (int i = 0; i < firstid; i++) {
            GameObject g = gObjectList[0];
            g.GetComponent<CRotateObject>().Set_isAccele(true);
            Accele(g);
        }
    }

    public void Inverse(GameObject g) {
        if (!g.GetComponent<CRotateObject>().Get_isInverse() &&
            !g.GetComponent<CRotateObject>().Get_isInverse2()) {
            // ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆãƒªã‚¹ãƒˆã‹ã‚‰å‰Šé™¤
            int i;
            i = Get_iRanking(g);

            g.GetComponent<CRotateObject>().Set_isInverse(true);
            Accele(g);
            g.GetComponent<CRotateObject>().Set_isSort(true);

            // ï¿½ï¿½ï¿½ÌƒIï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‹lï¿½ß‚ï¿½
            for (int j = i; j < gObjectList.Count;) {
                gObjectList[j].GetComponent<CRotateObject>().Set_isAccele(true);
                Accele(gObjectList[j]);
            }

            CRotateObject cs = g.GetComponent<CRotateObject>();
            cs.InvDegree();
        }
    }


    //// ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    //public void Accele(GameObject g) {
    //    // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    //    g.GetComponent<CRotateObject>().Set_isAccele(true);
    //}

    // ï¿½ÔŠugetter
    public float Get_fInterval() {
        return fInterval;
    }

    // ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½Xï¿½ggetter
    public List<GameObject> Get_gObjectList() {
        return gObjectList;
    }

    // ï¿½ï¿½ï¿½ï¿½ÌƒIï¿½uï¿½Wï¿½Fï¿½Nï¿½ggetter
    public GameObject Get_gObject(int id) {
        if (gObjectList.Count <= id) {
            return null;
        }
        else {
            return gObjectList[id];
        }
    }

    // ï¿½ï¿½ï¿½ï¿½getter
    public int Get_iRanking(GameObject g) {
        return gObjectList.IndexOf(g);
    }

    public int Get_iObjectNum() {
        return gObjectList.Count;
    }

    public float Get_fSpeed() {
        return fSpeed;
    }

    public float Get_fAcceleSpeed() {
        return fAcceleSpeed;
    }
}
